uplift: port functionality (bug 1915695)
mozilla-conduit/lando pull request #155
Opened 2024-11-22 20:27 UTC by zzzeid

WIP - DO NOT MERGE

2025-01-21 05:21 UTC, shtrom requested changes
I think the error-handling is `Uplift.post` is in the wrong order.

Apart from that (and a few more nits), this looks pretty good.

2025-01-21 05:21 UTC, shtrom commented on src/lando/api/legacy/uplift.py
> +def get_uplift_repositories() -> list:
Is there a type that we could make it a `list[]` of?

2025-01-21 05:21 UTC, shtrom commented on src/lando/ui/legacy/forms.py
> +        regex="D[0-9]+$",
We can make the RE stricter.

```suggestion
        regex="^D[0-9]+$",
```

2025-01-21 05:21 UTC, shtrom commented on src/lando/ui/legacy/forms.py
> +        repository = all_repos.get(repo_name)
Does this only select upliftable repos?

2025-01-21 05:21 UTC, shtrom commented on src/lando/ui/legacy/revisions.py
> +        if uplift_request_form.is_valid() and not errors:
`errors` will always be empty here, as it only gets set below on line 53. I'd suggest moving the error management LL52-64 up before this, and return early, and keep the happy case as the continuation of the method.

2025-01-21 05:23 UTC, shtrom commented
It might be worth adding some tests for the API bit, too.

2025-01-21 14:07 UTC, zzzeid commented on src/lando/ui/legacy/forms.py
> +        repository = all_repos.get(repo_name)
No, it will just verify that the repo is in fact a repo. I will clean up this section a little, but I think in the long run we should probably sync an "uplift" flag that is on the Repo object itself, and that way we can query these repos directly without contacting phabricator.

2025-01-21 14:13 UTC, zzzeid commented on src/lando/api/legacy/uplift.py
> +def get_uplift_repositories() -> list:
I can add that.

Side note: this is an early version of uplift functionality, and as part of updating the repo with all the changes in the lando-api and lando-ui repos, this code will be affected.

2025-01-21 23:42 UTC, shtrom commented on src/lando/ui/legacy/forms.py
> +        repository = all_repos.get(repo_name)
Yep. It might be worth having a deliberate action or command to sync from Phabricator, but otherwise not do it, or do it periodically rather than on demand. Looking in suite, I saw that lando fires a large number of requests at Phabricator, and reducing them could potentially make the whole experience faster.

2025-01-23 16:12 UTC, zzzeid commented
> It might be worth adding some tests for the API bit, too.

This is an early version of uplift, with an existing test that is marked as xfail. I don't want to add new functionality here that may be coming in from additional pulls from the legacy repos (which itself contains a few more change to the uplift functionality).

2025-01-23 23:34 UTC, shtrom approved these changes
LGTM!

2025-01-24 13:50 UTC, merged