landing_worker: fix handling of merge conflicts (bug 1938162)
mozilla-conduit/lando pull request #182
Opened 2024-12-19 05:57 UTC by shtrom

Add test coverage for good measure (and remove the never-used `job.error_breakdown["content"]`).

Much better!

Before:
![2024-12-19T16:54:18,990160289+11:00](https://github.com/user-attachments/assets/c3c4386f-30d6-4838-8860-c6e343ca7b6f)
After:
![2024-12-19T16:55:32,929871564+11:00](https://github.com/user-attachments/assets/2696e475-7feb-4d4b-af92-8c09868d29e5)

2024-12-19 14:01 UTC, zzzeid submitted a review, later dismissed
Looks good to me, just a couple of small changes.

2024-12-19 21:36 UTC, shtrom commented on src/lando/main/scm/abstract_scm.py
> +    def reject_path(cls) -> Path:
Yup. Python 3.13 is gonna deprecat abstract properties, which is a bit unfortunate in this case.

2024-12-19 21:46 UTC, shtrom commented on src/lando/api/tests/test_landings.py
> +def test_merge_conflict(
Agreed. I won't do it here, but I meant to do some cleanup as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1934485#c3

2024-12-20 14:03 UTC, zzzeid requested changes
Looks good, minus the unrelated changes that should be removed from this PR.

2024-12-20 14:03 UTC, zzzeid commented on src/lando/api/legacy/spec/swagger.yml
Unrelated change in this yaml file (looks like formatting). Also, wanted to take this opportunity to mention [bug 1927139](https://bugzilla.mozilla.org/show_bug.cgi?id=1927139).

2024-12-20 14:03 UTC, zzzeid commented on src/lando/ui/jinja2/stack/partials/timeline.html
Also unrelated change here to this html file.

We should probably add Jinja2 files to the linters and run them on all the templates though, in a separate PR.

2024-12-22 22:45 UTC, shtrom commented on src/lando/ui/jinja2/stack/partials/timeline.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1938838

2024-12-22 22:46 UTC, shtrom commented on src/lando/api/legacy/spec/swagger.yml
Ok, so this file needs to go.

2024-12-22 22:46 UTC, shtrom commented on src/lando/ui/jinja2/stack/partials/timeline.html
There is a change in the HTML file, though, so I thought I might as well lint it once and for all (in a separate commit), prior to making the change.

2025-01-07 22:01 UTC, zzzeid approved these changes

2025-01-07 22:01 UTC, zzzeid commented on src/lando/main/scm/abstract_scm.py
> +        return Path(".")
nit: can you add an explanation why this is set as the default? Is it ever used?

2025-01-07 22:08 UTC, shtrom commented on src/lando/main/scm/abstract_scm.py
> +        return Path(".")
Will do. It's used by the landing worker to locate the REJECTS, as Git and Hg put them in different locations https://github.com/mozilla-conduit/lando/pull/182/files#diff-15a775db92cbe9bf7e735238755c515149c96ba8bebb70ca8d0bbb1e0f9657daR164...

But the local directory seems like a reasonable default.

2025-01-08 03:11 UTC, merged