Add explicit sort ordering for 'LandingJobStatus' statuses using Case statement for `job_queue_query()`
mozilla-conduit/lando pull request #56
Opened 2024-05-07 23:01 UTC by ahochheiden

2024-05-08 13:45 UTC, zzzeid requested changes
Whenever a model is changed, `lando makemigrations` should be run to generate a migration file. Meant to add that as a make command as well.

2024-05-08 13:45 UTC, zzzeid commented on src/lando/main/models/landing_job.py
> +        q = q.annotate(custom_order=ordering).order_by("-custom_order", "-priority", "created_at")
nit
```suggestion
        q = q.annotate(status_order=ordering).order_by("-status_order", "-priority", "created_at")
```

2024-05-08 19:00 UTC, ahochheiden commented
> Whenever a model is changed, `lando makemigrations` should be run to generate a migration file. Meant to add that as a make command as well.

Done.

2024-05-08 19:00 UTC, ahochheiden commented on src/lando/main/models/landing_job.py
> +        q = q.annotate(custom_order=ordering).order_by("-custom_order", "-priority", "created_at")
Works for me.

2024-05-09 15:28 UTC, zzzeid approved these changes
lgtm!

one nit: if you look at previous commit message history, the first line is usually kept pretty short (on my machine, under 72 characters), and it matches the PR title before merge. You can keep it brief and put any additional detail in the rest of the message. On my machine, vim automatically breaks the line at that point. I think we have some exceptions here and there, and it's more of a convention/preference so I'll leave it up to you. We should probably have a proper styleguide for commits somewhere.

Looks like the average first line length is about 65 characters.

2024-05-15 19:06 UTC, merged