auth: add and use custom backend (bug 1899395)
mozilla-conduit/lando pull request #76
Opened 2024-06-03 15:31 UTC by zzzeid

2024-06-04 01:20 UTC, cgsheeh requested changes

2024-06-04 01:20 UTC, cgsheeh commented on src/lando/main/auth.py
> +class LandoOIDCAuthenticationBackend(OIDCAuthenticationBackend):
Add a docstring explaining the purpose of this class.

2024-06-06 15:12 UTC, cgsheeh approved these changes
r+, but again, just consider if we could `get_userinfo()` whenever we need it and avoid saving to the DB and dealing with syncing/expiration etc.

2024-06-06 16:21 UTC, zzzeid commented
> r+, but again, just consider if we could `get_userinfo()` whenever we need it and avoid saving to the DB and dealing with syncing/expiration etc.



> ust consider if we could `get_userinfo()` whenever we need it and avoid saving to the DB and dealing with syncing/expiration etc.

As mentioned in the other PR, leveraging the Django auth system abstraction is a core part of porting the auth functionality in Lando. Additional follow up PRs can fine tune this functionality and handle expiration/syncing (those are common problems that can be solved), but leveraging the framework as intended is good as a first step here.

2024-06-06 16:36 UTC, cgsheeh commented
> > r+, but again, just consider if we could get_userinfo() whenever we need it and avoid saving to the DB and dealing with syncing/expiration etc.
> 
> As mentioned in the other PR, leveraging the Django auth system abstraction is a core part of porting the auth functionality in Lando. Additional follow up PRs can fine tune this functionality and handle expiration/syncing (those are common problems that can be solved), but leveraging the framework as intended is good as a first step here.

I'm not suggesting we don't leverage the Django auth system, I'm asking if we need to store the data returned by Auth0 in the DB or if we can just request it when we need it and update the permissions accordingly.

2024-06-06 16:54 UTC, zzzeid commented
> > > r+, but again, just consider if we could get_userinfo() whenever we need it and avoid saving to the DB and dealing with syncing/expiration etc.
> > 
> > 
> > As mentioned in the other PR, leveraging the Django auth system abstraction is a core part of porting the auth functionality in Lando. Additional follow up PRs can fine tune this functionality and handle expiration/syncing (those are common problems that can be solved), but leveraging the framework as intended is good as a first step here.
> 
> I'm not suggesting we don't leverage the Django auth system, I'm asking if we need to store the data returned by Auth0 in the DB or if we can just request it when we need it and update the permissions accordingly.

RE: "avoid saving to the DB and dealing with syncing/expiration": There are things we need to store/sync, as I mentioned (e.g., nickname, avatar URL, name etc.) and those are things we are already doing in Lando today, just in a different way (flask-pyoidc is handling that and storing them in the session, as mentioned before). The group memberships happen to be in the same place, and for both of these things, there is no way around having to deal with syncing/expiration. The way we dealt with it in the legacy lando is to disregard the saved groups in the session, and fetching them as-needed. Moving the (re)fetching of userinfo to "when we need it" is one way to deal with syncing/expiration, and we may very well need to do that but as mentioned that will be handled in a follow up bug. Storing userinfo "as is" more or less follows what we are doing today in Lando for user-profile related things.

2024-06-06 17:36 UTC, merged